language: ruby
rvm:
- 2.5.3
- 2.6.1
install: bundle install --jobs=3 --retry=3
before_install:
- gem install bundler
deploy:
  provider: rubygems
  api_key:
    secure: rJJ80sKXVfLlV8hmQXCJ7PweCd1qs4QLzrRom631+1IXmjieuUkGnJsIMX/fQ0szsyGLV9FAtbGgYv9XfmP0Ur+zHzgCJikwLerRrKDtyKcpFaesL1zYlbHoEiz3aHWVU7OZT1h8QW6ZdXJPrQt93khoXrHEdt3YpEI3WBVHfI3kGdxTaJ3/y/Q4dxm0s2dUe/qoYn7P4OU3q1k9kGrduzUaiuTY+uyANSv6U84o5qs1Wag8v6SrDbcl8DPAFV/tkNkUB4RDRQSTTo/27u8o333KcbfOr/RVoutrjDTaGwrRb5yt4jOWahRwcDGg6vgkIdYjpHnJFMBtzEXUMRniFL5qjNgqi6LrPkGooyzQHjAMy53SGt7xTCksMYupIQYe3zaT72jtW+rA7XkgrhsXJ69wATdoYRAb0IJjyEkbrJB+duE5bL+oiyZfgQ257Ujk/inTWqRcCFo6G2pObh+wUAs7Aga8of7ojv8RJqwPKVenuAEWUFEJwMsXu9CwrwUqYHahu2DEPinMDCFk/r+CwKRDV3NgxMHAUPiSvNGcl0rSNBqovGDjLYrdLC5GkQ26dvbQF9wAu63zZv/9uIU+XJOB/kyAs+IrmpqdPGOncaN7mFyHW/8ty+VSDQhoNdY+Ki0ahy/YnuRKQky6Rg707yhwlc0A3rKnCw5VYVnpUfo=
  gem: lockie
  on:
    tags: true
    repo: melvinsembrano/lockie
