language: ruby
rvm:
- 2.5.3
- 2.6.1
install: bundle install --jobs=3 --retry=3
before_install:
- gem install bundler
deploy:
  api_key:
    secure: uLxYwSuJzZUqcFHKZ8Ebh6HfwhdIBPAR+Q996Lx/JnEbJxZP91cazU37CMtuaAZ6poa9eiD+LQhTFcPePFDybrt4xyqpv45Ju/bFaVt81/cW0m8yvlGOTofwZZe8yQ1vjgsVvb9VOOZSdZM1bKRKcdnHb71P9N0IQEA5aEWFZKwBNXr9EJYUHU/G6LKM2U62ri1qR/hbgoMYEkAVfUif09a4PImyBLTs9PTICTPC24vp3r92A++8CSnCVi+J3Axe0D1sf2YXwY72AObwHHwTjh08lpGb5Uxt0bk5nNOGMBbfLJ4eSreCYic9LFWHISOBy5gB26KKcMLSbjlhjIvbs8Sj/nz4wSpEq70jqYF/ZO9ukLHKLyj+vLgsyyK0arNRGRgVkXUutIc05fzpbiVSq+umWe/+65qfAqaCL6zjONlb1ubY35pPUeypxM4CwrK34oByoJrYNy1uDeZWwF3FuLJI/UBXZKDLsZwNWGBXgiwFCFVnQuiMhmeRVcxEC7Xmfhy7izpYO0n5TqapZuBlgcFVurynhhoDF9Fee4xLVlCRufWNLXL5ROECJ6Ed7rf+ollK3ewmv5NwTpb06Q0t7JOtPEZamPSjd59Vgjn5tH2KgI2Yme99edQgi/GTZaLmJSYyGhGcEb0tcHwR3CwtMpyZqxEuaP6FOM+XgSmzWEo=
